//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram")]

namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainClass DCMLRACPGProyectoIPSDiagram
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram.DisplayName", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("c8757630-e2ec-40cb-a818-4f0e74c6bb29")]
	public partial class DCMLRACPGProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.LightSteelBlue);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstracta)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstractaCShape newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstractaCShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Clase)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseCShape newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseCShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Atributo)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoShape newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Metodo)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoShape newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Parametro)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.ParametroShape newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.ParametroShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector(this.Partition);
				return newShape;
			}
			if(element is global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia)
			{
				global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConector newShape = new global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseCShape.DecoratorsInitialized += ClaseCShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstractaCShape.DecoratorsInitialized += ClaseAbstractaCShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoShape.DecoratorsInitialized += AtributoShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoShape.DecoratorsInitialized += MetodoShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.ParametroShape.DecoratorsInitialized += ParametroShapeDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.DecoratorsInitialized += AgregaConnectorDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.DecoratorsInitialized += AsociacionConectorDecoratorMap.OnDecoratorsInitialized;
			global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConector.DecoratorsInitialized += HerenciaConectorDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClaseCShape.
		/// </summary>
		internal static partial class ClaseCShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClaseCShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Clase.IdentificadorDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IDDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Clase.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Enriquecida").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.FondoColorBDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorB").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorB").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorG").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorG").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.FondoColorRDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorR").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FondoColorR").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.AlineacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Alineacion").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Alineacion").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.NombreColorRDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorB").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorB").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.NombreColorGDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorG").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorG").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.NombreColorBDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorR").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreColorR").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.TipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseEnriquecida.EnriquecidaDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ClaseAbstractaCShape.
		/// </summary>
		internal static partial class ClaseAbstractaCShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ClaseAbstractaCShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Clase.IdentificadorDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "IDDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Clase.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDeco").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AtributoShape.
		/// </summary>
		internal static partial class AtributoShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AtributoShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Atributo.NameTipoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "AtributoDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Enriquecido").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Enriquecido").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.ColorLetraBDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraB").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraB").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.ColorLetraGDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraG").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraG").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.ColorLetraRDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraR").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraR").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.FormatoBooleanoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FormatoBooleano").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "FormatoBooleano").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.TipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.AtributoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetodoShape.
		/// </summary>
		internal static partial class MetodoShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetodoShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Metodo.NameTipoRetornoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "MetodoDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Enriquecido").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Enriquecido").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.TipoLetraDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "TipoLetra").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.ColorLetraRDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraR").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraR").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.ColorLetraGDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraG").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraG").AssociateVisibilityWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.ColorLetraBDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraB").AssociateValueWith(shape.Store, propertyInfo);
		
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoEnriquecido.EnriquecidoDomainPropertyId);
				propertyInfo.FilteringValues.Add("True");
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "ColorLetraB").AssociateVisibilityWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ParametroShape.
		/// </summary>
		internal static partial class ParametroShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ParametroShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Parametro.DetallesDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "DetallesDeco").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AgregaConnector.
		/// </summary>
		internal static partial class AgregaConnectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AgregaConnector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMaxComponenteDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMaxComponenteDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMaxCompuestaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMaxCompuestoDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMinComponenteDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMinComponenteDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMinCompuestaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMinCompuestoDeco").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for AsociacionConector.
		/// </summary>
		internal static partial class AsociacionConectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for AsociacionConector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMaximaSourceDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMaxComponenteDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMaximaTargetDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMaxCompuestoDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMinimaSourceDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMinComponenteDeco").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMinimaTargetDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "CardMinCompuestoDeco").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for HerenciaConector.
		/// </summary>
		internal static partial class HerenciaConectorDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for HerenciaConector.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.DisjuntaSolapadaDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Solapacion").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.TotalParcialDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Totalidad").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::UPM_IPS.DCMLRACPGProyectoIPS.AgregacionConnectAction agregacionConnectAction;
		private global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConnectAction asociacionConnectAction;
		private global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConnectAction herenciaConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSToolboxHelper.AgregacionFilterString))
				{
					if (this.agregacionConnectAction == null)
					{
						this.agregacionConnectAction = new global::UPM_IPS.DCMLRACPGProyectoIPS.AgregacionConnectAction(this);
						this.agregacionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.agregacionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSToolboxHelper.AsociacionFilterString))
				{
					if (this.asociacionConnectAction == null)
					{
						this.asociacionConnectAction = new global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConnectAction(this);
						this.asociacionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.asociacionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSToolboxHelper.HerenciaFilterString))
				{
					if (this.herenciaConnectAction == null)
					{
						this.herenciaConnectAction = new global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConnectAction(this);
						this.herenciaConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.herenciaConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.agregacionConnectAction != null)
					{
						this.agregacionConnectAction.Dispose();
						this.agregacionConnectAction = null;
					}
					if(this.asociacionConnectAction != null)
					{
						this.asociacionConnectAction.Dispose();
						this.asociacionConnectAction = null;
					}
					if(this.herenciaConnectAction != null)
					{
						this.herenciaConnectAction.Dispose();
						this.herenciaConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// DCMLRACPGProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xc8757630, 0xe2ec, 0x40cb, 0xa8, 0x18, 0x4f, 0x0e, 0x74, 0xc6, 0xbb, 0x29);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DCMLRACPGProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DCMLRACPGProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstracta), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Clase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Atributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Metodo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Parametro), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstracta)
				{
					parentElement = GetParentForClaseAbstracta((global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseAbstracta)childElement);
				} else
				if(childElement is global::UPM_IPS.DCMLRACPGProyectoIPS.Clase)
				{
					parentElement = GetParentForClase((global::UPM_IPS.DCMLRACPGProyectoIPS.Clase)childElement);
				} else
				if(childElement is global::UPM_IPS.DCMLRACPGProyectoIPS.Atributo)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForAtributo(Atributo childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForAtributo((global::UPM_IPS.DCMLRACPGProyectoIPS.Atributo)childElement);
				} else
				if(childElement is global::UPM_IPS.DCMLRACPGProyectoIPS.Metodo)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForMetodo(Metodo childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForMetodo((global::UPM_IPS.DCMLRACPGProyectoIPS.Metodo)childElement);
				} else
				if(childElement is global::UPM_IPS.DCMLRACPGProyectoIPS.Parametro)
				{
					// Method:
					// private Microsoft.VisualStudio.Modeling.ModelElement GetParentForParametro(Parametro childElement)
					// {
					// }
					// must be implemented in a partial class of UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram.  Given a child element,
					// this method should return the parent model element that is associated with the shape or diagram that will be the parent 
					// of the shape created for this child.  If no shape should be created, the method should return null.
					parentElement = GetParentForParametro((global::UPM_IPS.DCMLRACPGProyectoIPS.Parametro)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::UPM_IPS.DCMLRACPGProyectoIPS.TapizModelo GetParentForClase( global::UPM_IPS.DCMLRACPGProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.DCMLRACPGProyectoIPS.TapizModelo result = root.TapizModelo;
				if ( result == null ) return null;
				return result;
			}
			public static global::UPM_IPS.DCMLRACPGProyectoIPS.TapizModelo GetParentForClaseAbstracta( global::UPM_IPS.DCMLRACPGProyectoIPS.Clase root )
			{
				// Segments 0 and 1
				global::UPM_IPS.DCMLRACPGProyectoIPS.TapizModelo result = root.TapizModelo;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.FindAgregaConnectorDecorator("NameDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMaxComponenteDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.FindAgregaConnectorDecorator("CardMaxComponenteDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMaxCompuestaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.FindAgregaConnectorDecorator("CardMaxCompuestoDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMinComponenteDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.FindAgregaConnectorDecorator("CardMinComponenteDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.CardMinCompuestaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AgregaConnector.FindAgregaConnectorDecorator("CardMinCompuestoDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.NombreDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.FindAsociacionConectorDecorator("NameDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMaximaSourceDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.FindAsociacionConectorDecorator("CardMaxComponenteDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMaximaTargetDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.FindAsociacionConectorDecorator("CardMaxCompuestoDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMinimaSourceDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.FindAsociacionConectorDecorator("CardMinComponenteDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.CardinalidadMinimaTargetDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.AsociacionConector.FindAsociacionConectorDecorator("CardMinCompuestoDeco");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.DisjuntaSolapadaDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConector.FindHerenciaConectorDecorator("Solapacion");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.TotalParcialDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::UPM_IPS.DCMLRACPGProyectoIPS.HerenciaConector.FindHerenciaConectorDecorator("Totalidad");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Agregacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Asociacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.Herencia), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram diagram = linkShape.Diagram as global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
