//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainModel DCMLRACPGProyectoIPSDomainModel
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel.DisplayName", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("428c4483-fcc4-4784-b083-8cfe50e00ecf")]
	public partial class DCMLRACPGProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DCMLRACPGProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x428c4483, 0xfcc4, 0x4784, 0xb0, 0x83, 0x8c, 0xfe, 0x50, 0xe0, 0x0e, 0xcf);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DCMLRACPGProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizModelo),
				typeof(Atributo),
				typeof(Parametro),
				typeof(ClaseAbstracta),
				typeof(Metodo),
				typeof(Clase),
				typeof(MétodoAbstracto),
				typeof(ClaseEnriquecida),
				typeof(MetodoEnriquecido),
				typeof(AtributoEnriquecido),
				typeof(MetodoHasParametro),
				typeof(TapizModeloHasClase),
				typeof(Agregacion),
				typeof(Asociacion),
				typeof(ClaseHasAtributo),
				typeof(ClaseHasMetodo),
				typeof(Herencia),
				typeof(ClaseAbstractaTieneMétodoAbstracto),
				typeof(DCMLRACPGProyectoIPSDiagram),
				typeof(AgregaConnector),
				typeof(AsociacionConector),
				typeof(HerenciaConector),
				typeof(AtributoShape),
				typeof(ParametroShape),
				typeof(ClaseCShape),
				typeof(ClaseAbstractaCShape),
				typeof(MetodoShape),
				typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram),
				typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DecoratorPropertyChanged),
				typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(Atributo), "Name", Atributo.NameDomainPropertyId, typeof(Atributo.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "TipoDatos", Atributo.TipoDatosDomainPropertyId, typeof(Atributo.TipoDatosPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "NameTipo", Atributo.NameTipoDomainPropertyId, typeof(Atributo.NameTipoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "Nombre", Parametro.NombreDomainPropertyId, typeof(Parametro.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "TipoDato", Parametro.TipoDatoDomainPropertyId, typeof(Parametro.TipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "TipoParametro", Parametro.TipoParametroDomainPropertyId, typeof(Parametro.TipoParametroPropertyHandler)),
				new DomainMemberInfo(typeof(Parametro), "Detalles", Parametro.DetallesDomainPropertyId, typeof(Parametro.DetallesPropertyHandler)),
				new DomainMemberInfo(typeof(Metodo), "Name", Metodo.NameDomainPropertyId, typeof(Metodo.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Metodo), "TipoRetorno", Metodo.TipoRetornoDomainPropertyId, typeof(Metodo.TipoRetornoPropertyHandler)),
				new DomainMemberInfo(typeof(Metodo), "NameTipoRetorno", Metodo.NameTipoRetornoDomainPropertyId, typeof(Metodo.NameTipoRetornoPropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "Name", Clase.NameDomainPropertyId, typeof(Clase.NamePropertyHandler)),
				new DomainMemberInfo(typeof(Clase), "Identificador", Clase.IdentificadorDomainPropertyId, typeof(Clase.IdentificadorPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "Enriquecida", ClaseEnriquecida.EnriquecidaDomainPropertyId, typeof(ClaseEnriquecida.EnriquecidaPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "FondoColorR", ClaseEnriquecida.FondoColorRDomainPropertyId, typeof(ClaseEnriquecida.FondoColorRPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "FondoColorG", ClaseEnriquecida.FondoColorGDomainPropertyId, typeof(ClaseEnriquecida.FondoColorGPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "FondoColorB", ClaseEnriquecida.FondoColorBDomainPropertyId, typeof(ClaseEnriquecida.FondoColorBPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "NombreColorR", ClaseEnriquecida.NombreColorRDomainPropertyId, typeof(ClaseEnriquecida.NombreColorRPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "NombreColorG", ClaseEnriquecida.NombreColorGDomainPropertyId, typeof(ClaseEnriquecida.NombreColorGPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "TipoLetra", ClaseEnriquecida.TipoLetraDomainPropertyId, typeof(ClaseEnriquecida.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "Alineacion", ClaseEnriquecida.AlineacionDomainPropertyId, typeof(ClaseEnriquecida.AlineacionPropertyHandler)),
				new DomainMemberInfo(typeof(ClaseEnriquecida), "NombreColorB", ClaseEnriquecida.NombreColorBDomainPropertyId, typeof(ClaseEnriquecida.NombreColorBPropertyHandler)),
				new DomainMemberInfo(typeof(MetodoEnriquecido), "TipoLetra", MetodoEnriquecido.TipoLetraDomainPropertyId, typeof(MetodoEnriquecido.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(MetodoEnriquecido), "ColorLetraR", MetodoEnriquecido.ColorLetraRDomainPropertyId, typeof(MetodoEnriquecido.ColorLetraRPropertyHandler)),
				new DomainMemberInfo(typeof(MetodoEnriquecido), "ColorLetraG", MetodoEnriquecido.ColorLetraGDomainPropertyId, typeof(MetodoEnriquecido.ColorLetraGPropertyHandler)),
				new DomainMemberInfo(typeof(MetodoEnriquecido), "ColorLetraB", MetodoEnriquecido.ColorLetraBDomainPropertyId, typeof(MetodoEnriquecido.ColorLetraBPropertyHandler)),
				new DomainMemberInfo(typeof(MetodoEnriquecido), "Enriquecido", MetodoEnriquecido.EnriquecidoDomainPropertyId, typeof(MetodoEnriquecido.EnriquecidoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "ColorLetraR", AtributoEnriquecido.ColorLetraRDomainPropertyId, typeof(AtributoEnriquecido.ColorLetraRPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "ColorLetraG", AtributoEnriquecido.ColorLetraGDomainPropertyId, typeof(AtributoEnriquecido.ColorLetraGPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "ColorLetraB", AtributoEnriquecido.ColorLetraBDomainPropertyId, typeof(AtributoEnriquecido.ColorLetraBPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "TipoLetra", AtributoEnriquecido.TipoLetraDomainPropertyId, typeof(AtributoEnriquecido.TipoLetraPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "FormatoBooleano", AtributoEnriquecido.FormatoBooleanoDomainPropertyId, typeof(AtributoEnriquecido.FormatoBooleanoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoEnriquecido), "Enriquecido", AtributoEnriquecido.EnriquecidoDomainPropertyId, typeof(AtributoEnriquecido.EnriquecidoPropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "Nombre", Agregacion.NombreDomainPropertyId, typeof(Agregacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "CardMinComponente", Agregacion.CardMinComponenteDomainPropertyId, typeof(Agregacion.CardMinComponentePropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "CardMaxComponente", Agregacion.CardMaxComponenteDomainPropertyId, typeof(Agregacion.CardMaxComponentePropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "CardMinCompuesta", Agregacion.CardMinCompuestaDomainPropertyId, typeof(Agregacion.CardMinCompuestaPropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "CardMaxCompuesta", Agregacion.CardMaxCompuestaDomainPropertyId, typeof(Agregacion.CardMaxCompuestaPropertyHandler)),
				new DomainMemberInfo(typeof(Agregacion), "TipoAgregación", Agregacion.TipoAgregaciónDomainPropertyId, typeof(Agregacion.TipoAgregaciónPropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "Nombre", Asociacion.NombreDomainPropertyId, typeof(Asociacion.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadMinimaSource", Asociacion.CardinalidadMinimaSourceDomainPropertyId, typeof(Asociacion.CardinalidadMinimaSourcePropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadMinimaTarget", Asociacion.CardinalidadMinimaTargetDomainPropertyId, typeof(Asociacion.CardinalidadMinimaTargetPropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadMaximaSource", Asociacion.CardinalidadMaximaSourceDomainPropertyId, typeof(Asociacion.CardinalidadMaximaSourcePropertyHandler)),
				new DomainMemberInfo(typeof(Asociacion), "CardinalidadMaximaTarget", Asociacion.CardinalidadMaximaTargetDomainPropertyId, typeof(Asociacion.CardinalidadMaximaTargetPropertyHandler)),
				new DomainMemberInfo(typeof(Herencia), "TotalParcial", Herencia.TotalParcialDomainPropertyId, typeof(Herencia.TotalParcialPropertyHandler)),
				new DomainMemberInfo(typeof(Herencia), "DisjuntaSolapada", Herencia.DisjuntaSolapadaDomainPropertyId, typeof(Herencia.DisjuntaSolapadaPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(MetodoHasParametro), "Metodo", MetodoHasParametro.MetodoDomainRoleId),
				new DomainRolePlayerInfo(typeof(MetodoHasParametro), "Parametro", MetodoHasParametro.ParametroDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizModeloHasClase), "TapizModelo", TapizModeloHasClase.TapizModeloDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizModeloHasClase), "Clase", TapizModeloHasClase.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Agregacion), "SourceClase", Agregacion.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Agregacion), "TargetClase", Agregacion.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Asociacion), "SourceClase", Asociacion.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Asociacion), "TargetClase", Asociacion.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Clase", ClaseHasAtributo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasAtributo), "Atributo", ClaseHasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasMetodo), "Clase", ClaseHasMetodo.ClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseHasMetodo), "Metodo", ClaseHasMetodo.MetodoDomainRoleId),
				new DomainRolePlayerInfo(typeof(Herencia), "SourceClase", Herencia.SourceClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(Herencia), "TargetClase", Herencia.TargetClaseDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAbstractaTieneMétodoAbstracto), "ClaseAbstracta", ClaseAbstractaTieneMétodoAbstracto.ClaseAbstractaDomainRoleId),
				new DomainRolePlayerInfo(typeof(ClaseAbstractaTieneMétodoAbstracto), "MétodoAbstracto", ClaseAbstractaTieneMétodoAbstracto.MétodoAbstractoDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(19);
				createElementMap.Add(typeof(TapizModelo), 0);
				createElementMap.Add(typeof(Atributo), 1);
				createElementMap.Add(typeof(Parametro), 2);
				createElementMap.Add(typeof(ClaseAbstracta), 3);
				createElementMap.Add(typeof(Metodo), 4);
				createElementMap.Add(typeof(Clase), 5);
				createElementMap.Add(typeof(MétodoAbstracto), 6);
				createElementMap.Add(typeof(DCMLRACPGProyectoIPSDiagram), 7);
				createElementMap.Add(typeof(AgregaConnector), 8);
				createElementMap.Add(typeof(AsociacionConector), 9);
				createElementMap.Add(typeof(HerenciaConector), 10);
				createElementMap.Add(typeof(AtributoShape), 11);
				createElementMap.Add(typeof(ParametroShape), 12);
				createElementMap.Add(typeof(ClaseCShape), 13);
				createElementMap.Add(typeof(ClaseAbstractaCShape), 14);
				createElementMap.Add(typeof(MetodoShape), 15);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizModelo(partition, propertyAssignments);
				case 1: return new Atributo(partition, propertyAssignments);
				case 2: return new Parametro(partition, propertyAssignments);
				case 3: return new ClaseAbstracta(partition, propertyAssignments);
				case 4: return new Metodo(partition, propertyAssignments);
				case 5: return new Clase(partition, propertyAssignments);
				case 6: return new MétodoAbstracto(partition, propertyAssignments);
				case 7: return new DCMLRACPGProyectoIPSDiagram(partition, propertyAssignments);
				case 8: return new AgregaConnector(partition, propertyAssignments);
				case 9: return new AsociacionConector(partition, propertyAssignments);
				case 10: return new HerenciaConector(partition, propertyAssignments);
				case 11: return new AtributoShape(partition, propertyAssignments);
				case 12: return new ParametroShape(partition, propertyAssignments);
				case 13: return new ClaseCShape(partition, propertyAssignments);
				case 14: return new ClaseAbstractaCShape(partition, propertyAssignments);
				case 15: return new MetodoShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(8);
				createElementLinkMap.Add(typeof(MetodoHasParametro), 0);
				createElementLinkMap.Add(typeof(TapizModeloHasClase), 1);
				createElementLinkMap.Add(typeof(Agregacion), 2);
				createElementLinkMap.Add(typeof(Asociacion), 3);
				createElementLinkMap.Add(typeof(ClaseHasAtributo), 4);
				createElementLinkMap.Add(typeof(ClaseHasMetodo), 5);
				createElementLinkMap.Add(typeof(Herencia), 6);
				createElementLinkMap.Add(typeof(ClaseAbstractaTieneMétodoAbstracto), 7);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new MetodoHasParametro(partition, roleAssignments, propertyAssignments);
				case 1: return new TapizModeloHasClase(partition, roleAssignments, propertyAssignments);
				case 2: return new Agregacion(partition, roleAssignments, propertyAssignments);
				case 3: return new Asociacion(partition, roleAssignments, propertyAssignments);
				case 4: return new ClaseHasAtributo(partition, roleAssignments, propertyAssignments);
				case 5: return new ClaseHasMetodo(partition, roleAssignments, propertyAssignments);
				case 6: return new Herencia(partition, roleAssignments, propertyAssignments);
				case 7: return new ClaseAbstractaTieneMétodoAbstracto(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DCMLRACPGProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DCMLRACPGProyectoIPSDomainModel.resourceManager == null)
				{
					DCMLRACPGProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DCMLRACPGProyectoIPSDomainModel).Assembly);
				}
				return DCMLRACPGProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DCMLRACPGProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DCMLRACPGProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DCMLRACPGProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DCMLRACPGProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DCMLRACPGProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return DCMLRACPGProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DCMLRACPGProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DCMLRACPGProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DCMLRACPGProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return DCMLRACPGProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCMLRACPGProyectoIPSDeleteClosure : DCMLRACPGProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCMLRACPGProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCMLRACPGProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DCMLRACPGProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::UPM_IPS.DCMLRACPGProyectoIPS.MetodoHasParametro.ParametroDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DCMLRACPGProyectoIPS.TapizModeloHasClase.ClaseDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseHasAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::UPM_IPS.DCMLRACPGProyectoIPS.ClaseHasMetodo.MetodoDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCMLRACPGProyectoIPSCopyClosure : DCMLRACPGProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCMLRACPGProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCMLRACPGProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCMLRACPGProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Cardinalidad
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidad
	{
		/// <summary>
		/// Uno
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad.Uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad/Uno.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Uno = 1,
		/// <summary>
		/// N
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad.N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad/N.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		N = 2,
		/// <summary>
		/// Cero
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad.Cero
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad/Cero.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Cero = 0,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoParametro
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoParametro
	{
		/// <summary>
		/// Entrada
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro.Entrada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro/Entrada.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Entrada = 0,
		/// <summary>
		/// Salida
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro.Salida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro/Salida.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Salida = 1,
		/// <summary>
		/// EntradaSalida
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro.EntradaSalida
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoParametro/EntradaSalida.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		EntradaSalida = 2,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoLetra
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoLetra
	{
		/// <summary>
		/// ComicSansMS
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra.ComicSansMS
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra/ComicSansMS.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		ComicSansMS = 2,
		/// <summary>
		/// Papyrus
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra.Papyrus
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra/Papyrus.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Papyrus = 3,
		/// <summary>
		/// Wingdings
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra.Wingdings
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra/Wingdings.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Wingdings = 4,
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra/Arial.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 0,
		/// <summary>
		/// Calibri
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra.Calibri
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra/Calibri.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Calibri = 1,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Cardinalidad1
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidad1
	{
		/// <summary>
		/// Uno
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1.Uno
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1/Uno.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Uno = 1,
		/// <summary>
		/// N
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1.N
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1/N.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		N = 2,
		/// <summary>
		/// Cero
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1.Cero
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Cardinalidad1/Cero.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Cero = 0,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Totalidad
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Totalidad
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Totalidad
	{
		/// <summary>
		/// Total
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Totalidad.Total
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Totalidad/Total.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Total = 1,
		/// <summary>
		/// Parcial
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Totalidad.Parcial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Totalidad/Parcial.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Parcial = 0,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Solapacion
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Solapacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Solapacion
	{
		/// <summary>
		/// Disjunta
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Solapacion.Disjunta
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Solapacion/Disjunta.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Disjunta = 0,
		/// <summary>
		/// Solapada
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Solapacion.Solapada
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Solapacion/Solapada.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Solapada = 1,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoAgregación
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoAgregación
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoAgregación
	{
		/// <summary>
		/// Inclusiva
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoAgregación.Inclusiva
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoAgregación/Inclusiva.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Inclusiva = 0,
		/// <summary>
		/// Referencial
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoAgregación.Referencial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoAgregación/Referencial.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Referencial = 1,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoLetra1
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoLetra1
	{
		/// <summary>
		/// ComicSansMS
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1.ComicSansMS
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1/ComicSansMS.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		ComicSansMS = 2,
		/// <summary>
		/// Papyrus
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1.Papyrus
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1/Papyrus.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Papyrus = 3,
		/// <summary>
		/// Wingdings
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1.Wingdings
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1/Wingdings.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Wingdings = 4,
		/// <summary>
		/// Arial
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1.Arial
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1/Arial.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Arial = 0,
		/// <summary>
		/// Calibri
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1.Calibri
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.TipoLetra1/Calibri.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Calibri = 1,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: FormatoBoolean
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.FormatoBoolean
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FormatoBoolean
	{
		/// <summary>
		/// Checkbox
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.FormatoBoolean.Checkbox
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.FormatoBoolean/Checkbox.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		Checkbox = 0,
		/// <summary>
		/// RadioButton
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.FormatoBoolean.RadioButton
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.FormatoBoolean/RadioButton.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		RadioButton = 1,
	}
}
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Alineacion
	/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Alineacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Alineacion
	{
		/// <summary>
		/// left
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Alineacion.left
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Alineacion/left.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		left = 0,
		/// <summary>
		/// center
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Alineacion.center
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Alineacion/center.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		center = 1,
		/// <summary>
		/// right
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Alineacion.right
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Alineacion/right.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		right = 2,
		/// <summary>
		/// justify
		/// Description for UPM_IPS.DCMLRACPGProyectoIPS.Alineacion.justify
		/// </summary>
		[DslDesign::DescriptionResource("UPM_IPS.DCMLRACPGProyectoIPS.Alineacion/justify.Description", typeof(global::UPM_IPS.DCMLRACPGProyectoIPS.DCMLRACPGProyectoIPSDomainModel), "UPM_IPS.DCMLRACPGProyectoIPS.GeneratedCode.DomainModelResx")]
		justify = 3,
	}
}

