//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DCMLRACPG_DSLProyIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DCMLRACPGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDCMLRACPGProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DCMLRACPGProyectoIPSPackageId = "8132dbac-9e08-4103-af90-a9f76e7d9f25";
		
		// Editor factory identifier
		public const string DCMLRACPGProyectoIPSEditorFactoryId = "706b78d9-9e8c-453e-be21-1fd2bf418387";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DCMLRACPGProyectoIPSModelExplorerToolWindowId = "e532fe49-9988-4aad-bd56-952e9fad6260";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Company.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DCMLRACPGProyectoIPSCommandSetId = "0ef9fd6f-c56c-43c6-bf90-2a2be049058f";
	}
}