//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DCMLRACPGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DCMLRACPGProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"UPM_IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DCMLRACPGProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDCMLRACPGProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCMLRACPGProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DCMLRACPGProyectoIPSPackageId = "376b96cb-2111-44a2-9672-1f05aa1c130a";
		
		// Editor factory identifier
		public const string DCMLRACPGProyectoIPSEditorFactoryId = "3ca63a9b-1b6f-431d-a04c-4a67b55592ca";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DCMLRACPGProyectoIPSModelExplorerToolWindowId = "a3835318-e5f5-4843-84c1-97a22113aa3b";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace UPM_IPS.DCMLRACPGProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DCMLRACPGProyectoIPSCommandSetId = "d1d81eac-e92f-49d7-b31d-e01374eeaf36";
	}
}